// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ExecutionStepStatus.
const (
	ExecutionStepStatusCompleted ExecutionStepStatus = "completed"
	ExecutionStepStatusFailed    ExecutionStepStatus = "failed"
	ExecutionStepStatusSkipped   ExecutionStepStatus = "skipped"
)

// Defines values for WorkflowExecutionResultStatus.
const (
	WorkflowExecutionResultStatusCompleted WorkflowExecutionResultStatus = "completed"
	WorkflowExecutionResultStatusFailed    WorkflowExecutionResultStatus = "failed"
	WorkflowExecutionResultStatusPartial   WorkflowExecutionResultStatus = "partial"
)

// Defines values for WorkflowNodeType.
const (
	Condition   WorkflowNodeType = "condition"
	Email       WorkflowNodeType = "email"
	End         WorkflowNodeType = "end"
	Form        WorkflowNodeType = "form"
	Integration WorkflowNodeType = "integration"
	Start       WorkflowNodeType = "start"
)

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// ExecutionStep defines model for ExecutionStep.
type ExecutionStep struct {
	// Description Description of what was executed
	Description *string `json:"description,omitempty"`

	// Error Error message if the step failed
	Error *string `json:"error,omitempty"`

	// Label Display label of the node
	Label *string `json:"label,omitempty"`

	// NodeId ID of the executed node
	NodeId string `json:"nodeId"`

	// Output Output data from this step
	Output *map[string]interface{} `json:"output,omitempty"`

	// Status Execution status of this step
	Status ExecutionStepStatus `json:"status"`

	// Type Type of the node
	Type string `json:"type"`
}

// ExecutionStepStatus Execution status of this step
type ExecutionStepStatus string

// NodeData defines model for NodeData.
type NodeData struct {
	// Description Description of what this node does
	Description *string `json:"description,omitempty"`

	// Label Display label for the node
	Label *string `json:"label,omitempty"`

	// Metadata Additional metadata for the node
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// Position defines model for Position.
type Position struct {
	// X X coordinate
	X *float32 `json:"x,omitempty"`

	// Y Y coordinate
	Y *float32 `json:"y,omitempty"`
}

// Workflow defines model for Workflow.
type Workflow struct {
	// Description Description of the workflow
	Description *string `json:"description,omitempty"`

	// Edges List of edges connecting the nodes
	Edges *[]WorkflowEdge `json:"edges,omitempty"`

	// Id Unique identifier for the workflow
	Id openapi_types.UUID `json:"id"`

	// Name Name of the workflow
	Name *string `json:"name,omitempty"`

	// Nodes List of nodes in the workflow
	Nodes *[]WorkflowNode `json:"nodes,omitempty"`
}

// WorkflowEdge defines model for WorkflowEdge.
type WorkflowEdge struct {
	// Animated Whether the edge should be animated
	Animated *bool `json:"animated,omitempty"`

	// Id Unique identifier for the edge
	Id string `json:"id"`

	// Label Label displayed on the edge
	Label *string `json:"label,omitempty"`

	// LabelStyle CSS style properties for the edge label
	LabelStyle *map[string]interface{} `json:"labelStyle,omitempty"`

	// Source Source node ID
	Source string `json:"source"`

	// SourceHandle Source handle identifier (for conditional nodes)
	SourceHandle *string `json:"sourceHandle,omitempty"`

	// Style CSS style properties for the edge
	Style *map[string]interface{} `json:"style,omitempty"`

	// Target Target node ID
	Target string `json:"target"`

	// Type Type of edge
	Type *string `json:"type,omitempty"`
}

// WorkflowExecutionInput Input data for workflow execution
type WorkflowExecutionInput struct {
	// Variables Input variables for the workflow
	Variables *map[string]interface{} `json:"variables,omitempty"`
}

// WorkflowExecutionResult defines model for WorkflowExecutionResult.
type WorkflowExecutionResult struct {
	// ExecutedAt Timestamp when the workflow was executed
	ExecutedAt time.Time `json:"executedAt"`

	// Status Overall execution status
	Status WorkflowExecutionResultStatus `json:"status"`

	// Steps Execution details for each step
	Steps *[]ExecutionStep `json:"steps,omitempty"`
}

// WorkflowExecutionResultStatus Overall execution status
type WorkflowExecutionResultStatus string

// WorkflowNode defines model for WorkflowNode.
type WorkflowNode struct {
	Data *NodeData `json:"data,omitempty"`

	// Id Unique identifier for the node
	Id       string    `json:"id"`
	Position *Position `json:"position,omitempty"`

	// Type Type of the node
	Type WorkflowNodeType `json:"type"`
}

// WorkflowNodeType Type of the node
type WorkflowNodeType string

// ExecuteWorkflowJSONRequestBody defines body for ExecuteWorkflow for application/json ContentType.
type ExecuteWorkflowJSONRequestBody = WorkflowExecutionInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get workflow by ID
	// (GET /workflow/{id})
	GetWorkflow(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Execute a workflow
	// (POST /workflow/{id}/execute)
	ExecuteWorkflow(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get workflow by ID
// (GET /workflow/{id})
func (_ Unimplemented) GetWorkflow(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Execute a workflow
// (POST /workflow/{id}/execute)
func (_ Unimplemented) ExecuteWorkflow(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetWorkflow operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecuteWorkflow operation middleware
func (siw *ServerInterfaceWrapper) ExecuteWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteWorkflow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workflow/{id}", wrapper.GetWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/workflow/{id}/execute", wrapper.ExecuteWorkflow)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYUW/bNhf9KwS/72ED7FhO7CzT09Km2AwUbdC0yLYiGGjx2mJLkSp55dQL/N8HkrJs",
	"WbTrtFmf9pZY1L2X5557eKgHmumi1AoUWpo+UJvlUDD/5wtjtHF/lEaXYFCA/xnWP3OwmRElCq1oGlaT",
	"Aqxlc6A9Cp9ZUUqgKb3V5uNM6nuiNJKZrhSnPYrL0j2zaISa09WqRw18qoQBTtP3dY67ZpmefoAM6apH",
	"X3yGrHIpbxDKbnGtmnZLvNr8R/SM3OcMyT2zBHxM4K2qr43OwFqSaSkhQ+CEM2SkTxQroEegYEL2iNQZ",
	"89E7O+odBRQRM4I5EItQkhkTEngslGRTkJENCVtKtiT+sduSC6U0b+P/zoIhE1VWGAvtlk94N/bkah1w",
	"DU838kybIhZTV+iypQ+UcS5cQCavt/qEpoLeTr7X/p0A8szogmAurMdlO+UDzQQuaUpvllzB0j1yjaAp",
	"ZVJk8Eu98CTTrjDXKprSS/fI1dVhk0WGlY30aM0yElYEKLbqUVXheOpmR0KgTtM9+1GUJXBH3w1U2ys7",
	"eIUfdot4uyxhb1Pj0O+MUd3belmz3dhcvdIcrhiyJxgpD5RLTbgG26r6GcyFIvfAMAdDshyyj+S+loev",
	"5v1MmzhGN8hMlPMFIOP1Zo9n6GWzkqwD7ObegTVGuWttxRrLNtCfuxv9nWRaGy4Uw9bW+sPzpOc5wNCR",
	"QWq2tVFVFVMwLtmyG/KPPSHPkiMixja0lvdvY44DcYsJmyY+DyRZU0ar0ARLmOLEguKESTBoowrM55FK",
	"6Eth0eX0j11IBRkKNW866YIJhMK/+38DM5rS/w02B+WgPiUH672/4PNtgWHGsKX7X0SE9Z0SnyoggoNC",
	"MRNgGhJF9z8eJ3AxSpI+nP487Y+GfNRnPw3P+6PR+fl4PBolSZLQrc5VlYhqTNDC3WJesQIOwn9bA3/p",
	"QCa3B2Y1ALcXbP+YCLWb6lE4O5Xq4ryjeoJHFa7Vqw5XmRIFc/Lc2cBtDh4BfxTyORCb60pyMgXSvLSF",
	"WFCOOvtUawlMPZ4KLlGrDzB8hD6+9LrIg0oCJ1rFg06UQMGk+Bv2Br/BZTh3j9fJ5zc3xLrXyAbi1saC",
	"btPYeawrk0VoeuN/D4fK5Kq1B7tP5EOs35jicn/E3D/e7sAPrtJGZpgMxP2xldPtOpryXwArBhMyMweM",
	"OAb/exSmfVbtsPXoMMYWWmNeu6DD5sPLUN3QpuSDg7k2XcGrdh2p2hhEbRoNqf1pMOHtoV4wI9hU1hN+",
	"dE9Coublg/r8DYa0R10ZDN0lgc4NMATzF+bMXyZyAzbXktP0dLw6ylh0YHwDtpIYucDVfv4yxiBRgEVW",
	"lOQ+h7ZW778qnSano34y7A/Hb4ej9CxJT0cnF+PzP7ePJc4Q+iiKPXMTt+GvF2CYlJsO13b8Sw68ZMbp",
	"2iMcuGP0wXsAB2RCBi4Ay/L1TeCo46t9af3S+bXVn4OWvXUods1X7W8P1dWY/kefTx2vvVeGyy2/e6iW",
	"xhc/6j5Us2CdHfy3hVrrhEKYm/X1vJH0ZkTvjqg/pml+Sbchbq1QM90t/PJ64oErmGJz5zOdda05rebN",
	"gHkLK7D9zeTyekJ7dAHGhljDk+Qk8XfsEhQrBU3p2UlycuZZj7lv/WAdcfAg+Mr9Ej0t3gAaAQsgbDPj",
	"HGZCeZjIdEkEWlLtcqDRLafUnKb0V8AtX1gywwpAMJam7zstzKEbMOI/hVvs9rPRTA/9phdBtwN5gqg9",
	"rWFe3blsttTKhnk6TRKv9lohqPBtoyylCJ9/Bh9sYPimoGPsbCDNjjGpsgysnVVSLompW8Q34Kx6dJSM",
	"nqyU8JEvUkfkq92qR8dPiMLe1BOFYJz1smAWYAjUC3vUVkXBzDKQbsPa6TLYHWRzx7qmdkvv3FvteRjU",
	"+uolU1vcp/qtubgXmHuSlkYvBAdORONGOgNRv/+kQ0FQrw/fr5qPo+j+qQKLzzRfPjnTd7xdtOlfcner",
	"7zCRu+bp0GA030Xt1siG+fwuQ7JgUrR4+J80eGnoju8+aXCv+TixsXypMyYJhwVIXRagsM5Je7QyzuDn",
	"iGU6GEi3LtcW04vkIhm4M3l1t/onAAD//+Cr7NJYGQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
