// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/db/workflow_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "workflow-code-test/api/pkg/db/models"

	gomock "github.com/golang/mock/gomock"
)

// MockWorkFlowDB is a mock of WorkFlowDB interface.
type MockWorkFlowDB struct {
	ctrl     *gomock.Controller
	recorder *MockWorkFlowDBMockRecorder
}

// MockWorkFlowDBMockRecorder is the mock recorder for MockWorkFlowDB.
type MockWorkFlowDBMockRecorder struct {
	mock *MockWorkFlowDB
}

// NewMockWorkFlowDB creates a new mock instance.
func NewMockWorkFlowDB(ctrl *gomock.Controller) *MockWorkFlowDB {
	mock := &MockWorkFlowDB{ctrl: ctrl}
	mock.recorder = &MockWorkFlowDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkFlowDB) EXPECT() *MockWorkFlowDBMockRecorder {
	return m.recorder
}

// GetWorkflowByID mocks base method.
func (m *MockWorkFlowDB) GetWorkflowByID(ctx context.Context, workflowID string) (*models.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowByID", ctx, workflowID)
	ret0, _ := ret[0].(*models.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowByID indicates an expected call of GetWorkflowByID.
func (mr *MockWorkFlowDBMockRecorder) GetWorkflowByID(ctx, workflowID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowByID", reflect.TypeOf((*MockWorkFlowDB)(nil).GetWorkflowByID), ctx, workflowID)
}
