// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("WorkflowEdgeToWorkflowUsingWorkflow", testWorkflowEdgeToOneWorkflowUsingWorkflow)
	t.Run("WorkflowNodeToWorkflowUsingWorkflow", testWorkflowNodeToOneWorkflowUsingWorkflow)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("WorkflowToWorkflowEdges", testWorkflowToManyWorkflowEdges)
	t.Run("WorkflowToWorkflowNodes", testWorkflowToManyWorkflowNodes)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("WorkflowEdgeToWorkflowUsingWorkflowEdges", testWorkflowEdgeToOneSetOpWorkflowUsingWorkflow)
	t.Run("WorkflowNodeToWorkflowUsingWorkflowNodes", testWorkflowNodeToOneSetOpWorkflowUsingWorkflow)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("WorkflowToWorkflowEdges", testWorkflowToManyAddOpWorkflowEdges)
	t.Run("WorkflowToWorkflowNodes", testWorkflowToManyAddOpWorkflowNodes)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}
