// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdges)
	t.Run("WorkflowNodes", testWorkflowNodes)
	t.Run("Workflows", testWorkflows)
}

func TestDelete(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesDelete)
	t.Run("WorkflowNodes", testWorkflowNodesDelete)
	t.Run("Workflows", testWorkflowsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesQueryDeleteAll)
	t.Run("WorkflowNodes", testWorkflowNodesQueryDeleteAll)
	t.Run("Workflows", testWorkflowsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesSliceDeleteAll)
	t.Run("WorkflowNodes", testWorkflowNodesSliceDeleteAll)
	t.Run("Workflows", testWorkflowsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesExists)
	t.Run("WorkflowNodes", testWorkflowNodesExists)
	t.Run("Workflows", testWorkflowsExists)
}

func TestFind(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesFind)
	t.Run("WorkflowNodes", testWorkflowNodesFind)
	t.Run("Workflows", testWorkflowsFind)
}

func TestBind(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesBind)
	t.Run("WorkflowNodes", testWorkflowNodesBind)
	t.Run("Workflows", testWorkflowsBind)
}

func TestOne(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesOne)
	t.Run("WorkflowNodes", testWorkflowNodesOne)
	t.Run("Workflows", testWorkflowsOne)
}

func TestAll(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesAll)
	t.Run("WorkflowNodes", testWorkflowNodesAll)
	t.Run("Workflows", testWorkflowsAll)
}

func TestCount(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesCount)
	t.Run("WorkflowNodes", testWorkflowNodesCount)
	t.Run("Workflows", testWorkflowsCount)
}

func TestHooks(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesHooks)
	t.Run("WorkflowNodes", testWorkflowNodesHooks)
	t.Run("Workflows", testWorkflowsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesInsert)
	t.Run("WorkflowEdges", testWorkflowEdgesInsertWhitelist)
	t.Run("WorkflowNodes", testWorkflowNodesInsert)
	t.Run("WorkflowNodes", testWorkflowNodesInsertWhitelist)
	t.Run("Workflows", testWorkflowsInsert)
	t.Run("Workflows", testWorkflowsInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesReload)
	t.Run("WorkflowNodes", testWorkflowNodesReload)
	t.Run("Workflows", testWorkflowsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesReloadAll)
	t.Run("WorkflowNodes", testWorkflowNodesReloadAll)
	t.Run("Workflows", testWorkflowsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesSelect)
	t.Run("WorkflowNodes", testWorkflowNodesSelect)
	t.Run("Workflows", testWorkflowsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesUpdate)
	t.Run("WorkflowNodes", testWorkflowNodesUpdate)
	t.Run("Workflows", testWorkflowsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesSliceUpdateAll)
	t.Run("WorkflowNodes", testWorkflowNodesSliceUpdateAll)
	t.Run("Workflows", testWorkflowsSliceUpdateAll)
}
