// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("WorkflowEdges", testWorkflowEdgesUpsert)

	t.Run("WorkflowNodes", testWorkflowNodesUpsert)

	t.Run("Workflows", testWorkflowsUpsert)
}
