// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Workflow is an object representing the database table.
type Workflow struct {
	ID          string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name        string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	CreatedAt   null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt   null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *workflowR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workflowL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkflowColumns = struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "id",
	Name:        "name",
	Description: "description",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var WorkflowTableColumns = struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "workflows.id",
	Name:        "workflows.name",
	Description: "workflows.description",
	CreatedAt:   "workflows.created_at",
	UpdatedAt:   "workflows.updated_at",
}

// Generated where

var WorkflowWhere = struct {
	ID          whereHelperstring
	Name        whereHelperstring
	Description whereHelpernull_String
	CreatedAt   whereHelpernull_Time
	UpdatedAt   whereHelpernull_Time
}{
	ID:          whereHelperstring{field: "\"workflows\".\"id\""},
	Name:        whereHelperstring{field: "\"workflows\".\"name\""},
	Description: whereHelpernull_String{field: "\"workflows\".\"description\""},
	CreatedAt:   whereHelpernull_Time{field: "\"workflows\".\"created_at\""},
	UpdatedAt:   whereHelpernull_Time{field: "\"workflows\".\"updated_at\""},
}

// WorkflowRels is where relationship names are stored.
var WorkflowRels = struct {
	WorkflowEdges string
	WorkflowNodes string
}{
	WorkflowEdges: "WorkflowEdges",
	WorkflowNodes: "WorkflowNodes",
}

// workflowR is where relationships are stored.
type workflowR struct {
	WorkflowEdges WorkflowEdgeSlice `boil:"WorkflowEdges" json:"WorkflowEdges" toml:"WorkflowEdges" yaml:"WorkflowEdges"`
	WorkflowNodes WorkflowNodeSlice `boil:"WorkflowNodes" json:"WorkflowNodes" toml:"WorkflowNodes" yaml:"WorkflowNodes"`
}

// NewStruct creates a new relationship struct
func (*workflowR) NewStruct() *workflowR {
	return &workflowR{}
}

func (o *Workflow) GetWorkflowEdges() WorkflowEdgeSlice {
	if o == nil {
		return nil
	}

	return o.R.GetWorkflowEdges()
}

func (r *workflowR) GetWorkflowEdges() WorkflowEdgeSlice {
	if r == nil {
		return nil
	}

	return r.WorkflowEdges
}

func (o *Workflow) GetWorkflowNodes() WorkflowNodeSlice {
	if o == nil {
		return nil
	}

	return o.R.GetWorkflowNodes()
}

func (r *workflowR) GetWorkflowNodes() WorkflowNodeSlice {
	if r == nil {
		return nil
	}

	return r.WorkflowNodes
}

// workflowL is where Load methods for each relationship are stored.
type workflowL struct{}

var (
	workflowAllColumns            = []string{"id", "name", "description", "created_at", "updated_at"}
	workflowColumnsWithoutDefault = []string{"name"}
	workflowColumnsWithDefault    = []string{"id", "description", "created_at", "updated_at"}
	workflowPrimaryKeyColumns     = []string{"id"}
	workflowGeneratedColumns      = []string{}
)

type (
	// WorkflowSlice is an alias for a slice of pointers to Workflow.
	// This should almost always be used instead of []Workflow.
	WorkflowSlice []*Workflow
	// WorkflowHook is the signature for custom Workflow hook methods
	WorkflowHook func(context.Context, boil.ContextExecutor, *Workflow) error

	workflowQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workflowType                 = reflect.TypeOf(&Workflow{})
	workflowMapping              = queries.MakeStructMapping(workflowType)
	workflowPrimaryKeyMapping, _ = queries.BindMapping(workflowType, workflowMapping, workflowPrimaryKeyColumns)
	workflowInsertCacheMut       sync.RWMutex
	workflowInsertCache          = make(map[string]insertCache)
	workflowUpdateCacheMut       sync.RWMutex
	workflowUpdateCache          = make(map[string]updateCache)
	workflowUpsertCacheMut       sync.RWMutex
	workflowUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workflowAfterSelectMu sync.Mutex
var workflowAfterSelectHooks []WorkflowHook

var workflowBeforeInsertMu sync.Mutex
var workflowBeforeInsertHooks []WorkflowHook
var workflowAfterInsertMu sync.Mutex
var workflowAfterInsertHooks []WorkflowHook

var workflowBeforeUpdateMu sync.Mutex
var workflowBeforeUpdateHooks []WorkflowHook
var workflowAfterUpdateMu sync.Mutex
var workflowAfterUpdateHooks []WorkflowHook

var workflowBeforeDeleteMu sync.Mutex
var workflowBeforeDeleteHooks []WorkflowHook
var workflowAfterDeleteMu sync.Mutex
var workflowAfterDeleteHooks []WorkflowHook

var workflowBeforeUpsertMu sync.Mutex
var workflowBeforeUpsertHooks []WorkflowHook
var workflowAfterUpsertMu sync.Mutex
var workflowAfterUpsertHooks []WorkflowHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Workflow) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflowAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Workflow) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflowBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Workflow) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflowAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Workflow) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflowBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Workflow) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflowAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Workflow) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflowBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Workflow) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflowAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Workflow) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflowBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Workflow) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflowAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkflowHook registers your hook function for all future operations.
func AddWorkflowHook(hookPoint boil.HookPoint, workflowHook WorkflowHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workflowAfterSelectMu.Lock()
		workflowAfterSelectHooks = append(workflowAfterSelectHooks, workflowHook)
		workflowAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workflowBeforeInsertMu.Lock()
		workflowBeforeInsertHooks = append(workflowBeforeInsertHooks, workflowHook)
		workflowBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workflowAfterInsertMu.Lock()
		workflowAfterInsertHooks = append(workflowAfterInsertHooks, workflowHook)
		workflowAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workflowBeforeUpdateMu.Lock()
		workflowBeforeUpdateHooks = append(workflowBeforeUpdateHooks, workflowHook)
		workflowBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workflowAfterUpdateMu.Lock()
		workflowAfterUpdateHooks = append(workflowAfterUpdateHooks, workflowHook)
		workflowAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workflowBeforeDeleteMu.Lock()
		workflowBeforeDeleteHooks = append(workflowBeforeDeleteHooks, workflowHook)
		workflowBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workflowAfterDeleteMu.Lock()
		workflowAfterDeleteHooks = append(workflowAfterDeleteHooks, workflowHook)
		workflowAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workflowBeforeUpsertMu.Lock()
		workflowBeforeUpsertHooks = append(workflowBeforeUpsertHooks, workflowHook)
		workflowBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workflowAfterUpsertMu.Lock()
		workflowAfterUpsertHooks = append(workflowAfterUpsertHooks, workflowHook)
		workflowAfterUpsertMu.Unlock()
	}
}

// One returns a single workflow record from the query.
func (q workflowQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Workflow, error) {
	o := &Workflow{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for workflows")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Workflow records from the query.
func (q workflowQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkflowSlice, error) {
	var o []*Workflow

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Workflow slice")
	}

	if len(workflowAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Workflow records in the query.
func (q workflowQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count workflows rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workflowQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if workflows exists")
	}

	return count > 0, nil
}

// WorkflowEdges retrieves all the workflow_edge's WorkflowEdges with an executor.
func (o *Workflow) WorkflowEdges(mods ...qm.QueryMod) workflow_edgeQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"workflow_edges\".\"workflow_id\"=?", o.ID),
	)

	return WorkflowEdges(queryMods...)
}

// WorkflowNodes retrieves all the workflow_node's WorkflowNodes with an executor.
func (o *Workflow) WorkflowNodes(mods ...qm.QueryMod) workflow_nodeQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"workflow_nodes\".\"workflow_id\"=?", o.ID),
	)

	return WorkflowNodes(queryMods...)
}

// LoadWorkflowEdges allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workflowL) LoadWorkflowEdges(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkflow any, mods queries.Applicator) error {
	var slice []*Workflow
	var object *Workflow

	if singular {
		var ok bool
		object, ok = maybeWorkflow.(*Workflow)
		if !ok {
			object = new(Workflow)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkflow)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkflow))
			}
		}
	} else {
		s, ok := maybeWorkflow.(*[]*Workflow)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkflow)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkflow))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workflowR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workflowR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workflow_edges`),
		qm.WhereIn(`workflow_edges.workflow_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load workflow_edges")
	}

	var resultSlice []*WorkflowEdge
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice workflow_edges")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on workflow_edges")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workflow_edges")
	}

	if len(workflow_edgeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.WorkflowEdges = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &workflow_edgeR{}
			}
			foreign.R.Workflow = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.WorkflowID {
				local.R.WorkflowEdges = append(local.R.WorkflowEdges, foreign)
				if foreign.R == nil {
					foreign.R = &workflow_edgeR{}
				}
				foreign.R.Workflow = local
				break
			}
		}
	}

	return nil
}

// LoadWorkflowNodes allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workflowL) LoadWorkflowNodes(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkflow any, mods queries.Applicator) error {
	var slice []*Workflow
	var object *Workflow

	if singular {
		var ok bool
		object, ok = maybeWorkflow.(*Workflow)
		if !ok {
			object = new(Workflow)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkflow)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkflow))
			}
		}
	} else {
		s, ok := maybeWorkflow.(*[]*Workflow)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkflow)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkflow))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workflowR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workflowR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workflow_nodes`),
		qm.WhereIn(`workflow_nodes.workflow_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load workflow_nodes")
	}

	var resultSlice []*WorkflowNode
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice workflow_nodes")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on workflow_nodes")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workflow_nodes")
	}

	if len(workflow_nodeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.WorkflowNodes = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &workflow_nodeR{}
			}
			foreign.R.Workflow = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.WorkflowID {
				local.R.WorkflowNodes = append(local.R.WorkflowNodes, foreign)
				if foreign.R == nil {
					foreign.R = &workflow_nodeR{}
				}
				foreign.R.Workflow = local
				break
			}
		}
	}

	return nil
}

// AddWorkflowEdges adds the given related objects to the existing relationships
// of the workflow, optionally inserting them as new records.
// Appends related to o.R.WorkflowEdges.
// Sets related.R.Workflow appropriately.
func (o *Workflow) AddWorkflowEdges(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WorkflowEdge) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WorkflowID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"workflow_edges\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"workflow_id"}),
				strmangle.WhereClause("\"", "\"", 2, workflow_edgePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WorkflowID = o.ID
		}
	}

	if o.R == nil {
		o.R = &workflowR{
			WorkflowEdges: related,
		}
	} else {
		o.R.WorkflowEdges = append(o.R.WorkflowEdges, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &workflow_edgeR{
				Workflow: o,
			}
		} else {
			rel.R.Workflow = o
		}
	}
	return nil
}

// AddWorkflowNodes adds the given related objects to the existing relationships
// of the workflow, optionally inserting them as new records.
// Appends related to o.R.WorkflowNodes.
// Sets related.R.Workflow appropriately.
func (o *Workflow) AddWorkflowNodes(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WorkflowNode) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WorkflowID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"workflow_nodes\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"workflow_id"}),
				strmangle.WhereClause("\"", "\"", 2, workflow_nodePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WorkflowID = o.ID
		}
	}

	if o.R == nil {
		o.R = &workflowR{
			WorkflowNodes: related,
		}
	} else {
		o.R.WorkflowNodes = append(o.R.WorkflowNodes, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &workflow_nodeR{
				Workflow: o,
			}
		} else {
			rel.R.Workflow = o
		}
	}
	return nil
}

// Workflows retrieves all the records using an executor.
func Workflows(mods ...qm.QueryMod) workflowQuery {
	mods = append(mods, qm.From("\"workflows\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workflows\".*"})
	}

	return workflowQuery{q}
}

// FindWorkflow retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkflow(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Workflow, error) {
	workflowObj := &Workflow{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workflows\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workflowObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from workflows")
	}

	if err = workflowObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workflowObj, err
	}

	return workflowObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Workflow) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no workflows provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workflowColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workflowInsertCacheMut.RLock()
	cache, cached := workflowInsertCache[key]
	workflowInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workflowAllColumns,
			workflowColumnsWithDefault,
			workflowColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workflowType, workflowMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workflowType, workflowMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workflows\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workflows\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into workflows")
	}

	if !cached {
		workflowInsertCacheMut.Lock()
		workflowInsertCache[key] = cache
		workflowInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Workflow.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Workflow) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workflowUpdateCacheMut.RLock()
	cache, cached := workflowUpdateCache[key]
	workflowUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workflowAllColumns,
			workflowPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update workflows, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workflows\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workflowPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workflowType, workflowMapping, append(wl, workflowPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update workflows row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for workflows")
	}

	if !cached {
		workflowUpdateCacheMut.Lock()
		workflowUpdateCache[key] = cache
		workflowUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workflowQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for workflows")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for workflows")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkflowSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workflowPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workflows\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workflowPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in workflow slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all workflow")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Workflow) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no workflows provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workflowColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workflowUpsertCacheMut.RLock()
	cache, cached := workflowUpsertCache[key]
	workflowUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workflowAllColumns,
			workflowColumnsWithDefault,
			workflowColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workflowAllColumns,
			workflowPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert workflows, could not build update column list")
		}

		ret := strmangle.SetComplement(workflowAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workflowPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert workflows, could not build conflict column list")
			}

			conflict = make([]string, len(workflowPrimaryKeyColumns))
			copy(conflict, workflowPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workflows\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workflowType, workflowMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workflowType, workflowMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert workflows")
	}

	if !cached {
		workflowUpsertCacheMut.Lock()
		workflowUpsertCache[key] = cache
		workflowUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Workflow record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Workflow) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Workflow provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workflowPrimaryKeyMapping)
	sql := "DELETE FROM \"workflows\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from workflows")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for workflows")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workflowQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no workflowQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from workflows")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for workflows")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkflowSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workflowBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workflowPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workflows\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workflowPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from workflow slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for workflows")
	}

	if len(workflowAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Workflow) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkflow(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkflowSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkflowSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workflowPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workflows\".* FROM \"workflows\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workflowPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WorkflowSlice")
	}

	*o = slice

	return nil
}

// WorkflowExists checks if the Workflow row exists.
func WorkflowExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workflows\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if workflows exists")
	}

	return exists, nil
}

// Exists checks if the Workflow row exists.
func (o *Workflow) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkflowExists(ctx, exec, o.ID)
}
