// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWorkflowNodes(t *testing.T) {
	t.Parallel()

	query := WorkflowNodes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWorkflowNodesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkflowNodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkflowNodesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := WorkflowNodes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkflowNodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkflowNodesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkflowNodeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkflowNodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkflowNodesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WorkflowNodeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if WorkflowNode exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WorkflowNodeExists to return true, but got false.")
	}
}

func testWorkflowNodesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	workflow_nodeFound, err := FindWorkflowNode(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if workflow_nodeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWorkflowNodesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = WorkflowNodes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWorkflowNodesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := WorkflowNodes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWorkflowNodesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	workflow_nodeOne := &WorkflowNode{}
	workflow_nodeTwo := &WorkflowNode{}
	if err = randomize.Struct(seed, workflow_nodeOne, workflow_nodeDBTypes, false, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}
	if err = randomize.Struct(seed, workflow_nodeTwo, workflow_nodeDBTypes, false, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workflow_nodeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workflow_nodeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkflowNodes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWorkflowNodesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	workflow_nodeOne := &WorkflowNode{}
	workflow_nodeTwo := &WorkflowNode{}
	if err = randomize.Struct(seed, workflow_nodeOne, workflow_nodeDBTypes, false, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}
	if err = randomize.Struct(seed, workflow_nodeTwo, workflow_nodeDBTypes, false, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workflow_nodeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workflow_nodeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkflowNodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func workflow_nodeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowNode) error {
	*o = WorkflowNode{}
	return nil
}

func workflow_nodeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowNode) error {
	*o = WorkflowNode{}
	return nil
}

func workflow_nodeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowNode) error {
	*o = WorkflowNode{}
	return nil
}

func workflow_nodeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowNode) error {
	*o = WorkflowNode{}
	return nil
}

func workflow_nodeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowNode) error {
	*o = WorkflowNode{}
	return nil
}

func workflow_nodeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowNode) error {
	*o = WorkflowNode{}
	return nil
}

func workflow_nodeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowNode) error {
	*o = WorkflowNode{}
	return nil
}

func workflow_nodeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowNode) error {
	*o = WorkflowNode{}
	return nil
}

func workflow_nodeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowNode) error {
	*o = WorkflowNode{}
	return nil
}

func testWorkflowNodesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &WorkflowNode{}
	o := &WorkflowNode{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize WorkflowNode object: %s", err)
	}

	AddWorkflowNodeHook(boil.BeforeInsertHook, workflow_nodeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	workflow_nodeBeforeInsertHooks = []WorkflowNodeHook{}

	AddWorkflowNodeHook(boil.AfterInsertHook, workflow_nodeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	workflow_nodeAfterInsertHooks = []WorkflowNodeHook{}

	AddWorkflowNodeHook(boil.AfterSelectHook, workflow_nodeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	workflow_nodeAfterSelectHooks = []WorkflowNodeHook{}

	AddWorkflowNodeHook(boil.BeforeUpdateHook, workflow_nodeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	workflow_nodeBeforeUpdateHooks = []WorkflowNodeHook{}

	AddWorkflowNodeHook(boil.AfterUpdateHook, workflow_nodeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	workflow_nodeAfterUpdateHooks = []WorkflowNodeHook{}

	AddWorkflowNodeHook(boil.BeforeDeleteHook, workflow_nodeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	workflow_nodeBeforeDeleteHooks = []WorkflowNodeHook{}

	AddWorkflowNodeHook(boil.AfterDeleteHook, workflow_nodeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	workflow_nodeAfterDeleteHooks = []WorkflowNodeHook{}

	AddWorkflowNodeHook(boil.BeforeUpsertHook, workflow_nodeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	workflow_nodeBeforeUpsertHooks = []WorkflowNodeHook{}

	AddWorkflowNodeHook(boil.AfterUpsertHook, workflow_nodeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	workflow_nodeAfterUpsertHooks = []WorkflowNodeHook{}
}

func testWorkflowNodesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkflowNodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkflowNodesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(workflow_nodePrimaryKeyColumns, workflow_nodeColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := WorkflowNodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkflowNodeToOneWorkflowUsingWorkflow(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local WorkflowNode
	var foreign Workflow

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, workflow_nodeDBTypes, false, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, workflowDBTypes, false, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.WorkflowID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Workflow().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddWorkflowHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := WorkflowNodeSlice{&local}
	if err = local.L.LoadWorkflow(ctx, tx, false, (*[]*WorkflowNode)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Workflow == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Workflow = nil
	if err = local.L.LoadWorkflow(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Workflow == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testWorkflowNodeToOneSetOpWorkflowUsingWorkflow(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a WorkflowNode
	var b, c Workflow

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workflow_nodeDBTypes, false, strmangle.SetComplement(workflow_nodePrimaryKeyColumns, workflow_nodeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, workflowDBTypes, false, strmangle.SetComplement(workflowPrimaryKeyColumns, workflowColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, workflowDBTypes, false, strmangle.SetComplement(workflowPrimaryKeyColumns, workflowColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Workflow{&b, &c} {
		err = a.SetWorkflow(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Workflow != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.WorkflowNodes[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.WorkflowID != x.ID {
			t.Error("foreign key was wrong value", a.WorkflowID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.WorkflowID))
		reflect.Indirect(reflect.ValueOf(&a.WorkflowID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.WorkflowID != x.ID {
			t.Error("foreign key was wrong value", a.WorkflowID, x.ID)
		}
	}
}

func testWorkflowNodesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkflowNodesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkflowNodeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkflowNodesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkflowNodes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	workflow_nodeDBTypes = map[string]string{`ID`: `uuid`, `WorkflowID`: `uuid`, `NodeID`: `character varying`, `Type`: `character varying`, `Position`: `jsonb`, `Data`: `jsonb`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                    = bytes.MinRead
)

func testWorkflowNodesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(workflow_nodePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(workflow_nodeAllColumns) == len(workflow_nodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkflowNodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWorkflowNodesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(workflow_nodeAllColumns) == len(workflow_nodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowNode{}
	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkflowNodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workflow_nodeDBTypes, true, workflow_nodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(workflow_nodeAllColumns, workflow_nodePrimaryKeyColumns) {
		fields = workflow_nodeAllColumns
	} else {
		fields = strmangle.SetComplement(
			workflow_nodeAllColumns,
			workflow_nodePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WorkflowNodeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWorkflowNodesUpsert(t *testing.T) {
	t.Parallel()

	if len(workflow_nodeAllColumns) == len(workflow_nodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := WorkflowNode{}
	if err = randomize.Struct(seed, &o, workflow_nodeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkflowNode: %s", err)
	}

	count, err := WorkflowNodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, workflow_nodeDBTypes, false, workflow_nodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkflowNode struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkflowNode: %s", err)
	}

	count, err = WorkflowNodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
