// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWorkflowEdges(t *testing.T) {
	t.Parallel()

	query := WorkflowEdges()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWorkflowEdgesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkflowEdges().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkflowEdgesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := WorkflowEdges().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkflowEdges().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkflowEdgesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkflowEdgeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkflowEdges().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkflowEdgesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WorkflowEdgeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if WorkflowEdge exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WorkflowEdgeExists to return true, but got false.")
	}
}

func testWorkflowEdgesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	workflow_edgeFound, err := FindWorkflowEdge(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if workflow_edgeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWorkflowEdgesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = WorkflowEdges().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWorkflowEdgesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := WorkflowEdges().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWorkflowEdgesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	workflow_edgeOne := &WorkflowEdge{}
	workflow_edgeTwo := &WorkflowEdge{}
	if err = randomize.Struct(seed, workflow_edgeOne, workflow_edgeDBTypes, false, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}
	if err = randomize.Struct(seed, workflow_edgeTwo, workflow_edgeDBTypes, false, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workflow_edgeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workflow_edgeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkflowEdges().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWorkflowEdgesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	workflow_edgeOne := &WorkflowEdge{}
	workflow_edgeTwo := &WorkflowEdge{}
	if err = randomize.Struct(seed, workflow_edgeOne, workflow_edgeDBTypes, false, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}
	if err = randomize.Struct(seed, workflow_edgeTwo, workflow_edgeDBTypes, false, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workflow_edgeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workflow_edgeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkflowEdges().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func workflow_edgeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowEdge) error {
	*o = WorkflowEdge{}
	return nil
}

func workflow_edgeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowEdge) error {
	*o = WorkflowEdge{}
	return nil
}

func workflow_edgeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowEdge) error {
	*o = WorkflowEdge{}
	return nil
}

func workflow_edgeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowEdge) error {
	*o = WorkflowEdge{}
	return nil
}

func workflow_edgeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowEdge) error {
	*o = WorkflowEdge{}
	return nil
}

func workflow_edgeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowEdge) error {
	*o = WorkflowEdge{}
	return nil
}

func workflow_edgeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowEdge) error {
	*o = WorkflowEdge{}
	return nil
}

func workflow_edgeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowEdge) error {
	*o = WorkflowEdge{}
	return nil
}

func workflow_edgeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkflowEdge) error {
	*o = WorkflowEdge{}
	return nil
}

func testWorkflowEdgesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &WorkflowEdge{}
	o := &WorkflowEdge{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge object: %s", err)
	}

	AddWorkflowEdgeHook(boil.BeforeInsertHook, workflow_edgeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	workflow_edgeBeforeInsertHooks = []WorkflowEdgeHook{}

	AddWorkflowEdgeHook(boil.AfterInsertHook, workflow_edgeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	workflow_edgeAfterInsertHooks = []WorkflowEdgeHook{}

	AddWorkflowEdgeHook(boil.AfterSelectHook, workflow_edgeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	workflow_edgeAfterSelectHooks = []WorkflowEdgeHook{}

	AddWorkflowEdgeHook(boil.BeforeUpdateHook, workflow_edgeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	workflow_edgeBeforeUpdateHooks = []WorkflowEdgeHook{}

	AddWorkflowEdgeHook(boil.AfterUpdateHook, workflow_edgeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	workflow_edgeAfterUpdateHooks = []WorkflowEdgeHook{}

	AddWorkflowEdgeHook(boil.BeforeDeleteHook, workflow_edgeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	workflow_edgeBeforeDeleteHooks = []WorkflowEdgeHook{}

	AddWorkflowEdgeHook(boil.AfterDeleteHook, workflow_edgeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	workflow_edgeAfterDeleteHooks = []WorkflowEdgeHook{}

	AddWorkflowEdgeHook(boil.BeforeUpsertHook, workflow_edgeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	workflow_edgeBeforeUpsertHooks = []WorkflowEdgeHook{}

	AddWorkflowEdgeHook(boil.AfterUpsertHook, workflow_edgeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	workflow_edgeAfterUpsertHooks = []WorkflowEdgeHook{}
}

func testWorkflowEdgesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkflowEdges().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkflowEdgesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(workflow_edgePrimaryKeyColumns, workflow_edgeColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := WorkflowEdges().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkflowEdgeToOneWorkflowUsingWorkflow(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local WorkflowEdge
	var foreign Workflow

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, workflow_edgeDBTypes, false, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, workflowDBTypes, false, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.WorkflowID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Workflow().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddWorkflowHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := WorkflowEdgeSlice{&local}
	if err = local.L.LoadWorkflow(ctx, tx, false, (*[]*WorkflowEdge)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Workflow == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Workflow = nil
	if err = local.L.LoadWorkflow(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Workflow == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testWorkflowEdgeToOneSetOpWorkflowUsingWorkflow(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a WorkflowEdge
	var b, c Workflow

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workflow_edgeDBTypes, false, strmangle.SetComplement(workflow_edgePrimaryKeyColumns, workflow_edgeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, workflowDBTypes, false, strmangle.SetComplement(workflowPrimaryKeyColumns, workflowColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, workflowDBTypes, false, strmangle.SetComplement(workflowPrimaryKeyColumns, workflowColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Workflow{&b, &c} {
		err = a.SetWorkflow(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Workflow != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.WorkflowEdges[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.WorkflowID != x.ID {
			t.Error("foreign key was wrong value", a.WorkflowID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.WorkflowID))
		reflect.Indirect(reflect.ValueOf(&a.WorkflowID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.WorkflowID != x.ID {
			t.Error("foreign key was wrong value", a.WorkflowID, x.ID)
		}
	}
}

func testWorkflowEdgesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkflowEdgesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkflowEdgeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkflowEdgesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkflowEdges().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	workflow_edgeDBTypes = map[string]string{`ID`: `uuid`, `WorkflowID`: `uuid`, `EdgeID`: `character varying`, `Source`: `character varying`, `Target`: `character varying`, `SourceHandle`: `character varying`, `Type`: `character varying`, `Animated`: `boolean`, `Style`: `jsonb`, `Label`: `character varying`, `LabelStyle`: `jsonb`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                    = bytes.MinRead
)

func testWorkflowEdgesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(workflow_edgePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(workflow_edgeAllColumns) == len(workflow_edgePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkflowEdges().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWorkflowEdgesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(workflow_edgeAllColumns) == len(workflow_edgePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkflowEdge{}
	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkflowEdges().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workflow_edgeDBTypes, true, workflow_edgePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(workflow_edgeAllColumns, workflow_edgePrimaryKeyColumns) {
		fields = workflow_edgeAllColumns
	} else {
		fields = strmangle.SetComplement(
			workflow_edgeAllColumns,
			workflow_edgePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WorkflowEdgeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWorkflowEdgesUpsert(t *testing.T) {
	t.Parallel()

	if len(workflow_edgeAllColumns) == len(workflow_edgePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := WorkflowEdge{}
	if err = randomize.Struct(seed, &o, workflow_edgeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkflowEdge: %s", err)
	}

	count, err := WorkflowEdges().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, workflow_edgeDBTypes, false, workflow_edgePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkflowEdge struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkflowEdge: %s", err)
	}

	count, err = WorkflowEdges().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
