// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WorkflowEdge is an object representing the database table.
type WorkflowEdge struct {
	ID           string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	WorkflowID   string      `boil:"workflow_id" json:"workflow_id" toml:"workflow_id" yaml:"workflow_id"`
	EdgeID       string      `boil:"edge_id" json:"edge_id" toml:"edge_id" yaml:"edge_id"`
	Source       string      `boil:"source" json:"source" toml:"source" yaml:"source"`
	Target       string      `boil:"target" json:"target" toml:"target" yaml:"target"`
	SourceHandle null.String `boil:"source_handle" json:"source_handle,omitempty" toml:"source_handle" yaml:"source_handle,omitempty"`
	Type         null.String `boil:"type" json:"type,omitempty" toml:"type" yaml:"type,omitempty"`
	Animated     null.Bool   `boil:"animated" json:"animated,omitempty" toml:"animated" yaml:"animated,omitempty"`
	Style        null.JSON   `boil:"style" json:"style,omitempty" toml:"style" yaml:"style,omitempty"`
	Label        null.String `boil:"label" json:"label,omitempty" toml:"label" yaml:"label,omitempty"`
	LabelStyle   null.JSON   `boil:"label_style" json:"label_style,omitempty" toml:"label_style" yaml:"label_style,omitempty"`
	CreatedAt    null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *workflow_edgeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workflow_edgeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkflowEdgeColumns = struct {
	ID           string
	WorkflowID   string
	EdgeID       string
	Source       string
	Target       string
	SourceHandle string
	Type         string
	Animated     string
	Style        string
	Label        string
	LabelStyle   string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	WorkflowID:   "workflow_id",
	EdgeID:       "edge_id",
	Source:       "source",
	Target:       "target",
	SourceHandle: "source_handle",
	Type:         "type",
	Animated:     "animated",
	Style:        "style",
	Label:        "label",
	LabelStyle:   "label_style",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var WorkflowEdgeTableColumns = struct {
	ID           string
	WorkflowID   string
	EdgeID       string
	Source       string
	Target       string
	SourceHandle string
	Type         string
	Animated     string
	Style        string
	Label        string
	LabelStyle   string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "workflow_edges.id",
	WorkflowID:   "workflow_edges.workflow_id",
	EdgeID:       "workflow_edges.edge_id",
	Source:       "workflow_edges.source",
	Target:       "workflow_edges.target",
	SourceHandle: "workflow_edges.source_handle",
	Type:         "workflow_edges.type",
	Animated:     "workflow_edges.animated",
	Style:        "workflow_edges.style",
	Label:        "workflow_edges.label",
	LabelStyle:   "workflow_edges.label_style",
	CreatedAt:    "workflow_edges.created_at",
	UpdatedAt:    "workflow_edges.updated_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Bool struct{ field string }

func (w whereHelpernull_Bool) EQ(x null.Bool) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Bool) NEQ(x null.Bool) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Bool) LT(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Bool) LTE(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Bool) GT(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Bool) GTE(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Bool) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Bool) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_JSON struct{ field string }

func (w whereHelpernull_JSON) EQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_JSON) NEQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_JSON) LT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_JSON) LTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_JSON) GT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_JSON) GTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_JSON) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_JSON) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var WorkflowEdgeWhere = struct {
	ID           whereHelperstring
	WorkflowID   whereHelperstring
	EdgeID       whereHelperstring
	Source       whereHelperstring
	Target       whereHelperstring
	SourceHandle whereHelpernull_String
	Type         whereHelpernull_String
	Animated     whereHelpernull_Bool
	Style        whereHelpernull_JSON
	Label        whereHelpernull_String
	LabelStyle   whereHelpernull_JSON
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
}{
	ID:           whereHelperstring{field: "\"workflow_edges\".\"id\""},
	WorkflowID:   whereHelperstring{field: "\"workflow_edges\".\"workflow_id\""},
	EdgeID:       whereHelperstring{field: "\"workflow_edges\".\"edge_id\""},
	Source:       whereHelperstring{field: "\"workflow_edges\".\"source\""},
	Target:       whereHelperstring{field: "\"workflow_edges\".\"target\""},
	SourceHandle: whereHelpernull_String{field: "\"workflow_edges\".\"source_handle\""},
	Type:         whereHelpernull_String{field: "\"workflow_edges\".\"type\""},
	Animated:     whereHelpernull_Bool{field: "\"workflow_edges\".\"animated\""},
	Style:        whereHelpernull_JSON{field: "\"workflow_edges\".\"style\""},
	Label:        whereHelpernull_String{field: "\"workflow_edges\".\"label\""},
	LabelStyle:   whereHelpernull_JSON{field: "\"workflow_edges\".\"label_style\""},
	CreatedAt:    whereHelpernull_Time{field: "\"workflow_edges\".\"created_at\""},
	UpdatedAt:    whereHelpernull_Time{field: "\"workflow_edges\".\"updated_at\""},
}

// WorkflowEdgeRels is where relationship names are stored.
var WorkflowEdgeRels = struct {
	Workflow string
}{
	Workflow: "Workflow",
}

// workflow_edgeR is where relationships are stored.
type workflow_edgeR struct {
	Workflow *Workflow `boil:"Workflow" json:"Workflow" toml:"Workflow" yaml:"Workflow"`
}

// NewStruct creates a new relationship struct
func (*workflow_edgeR) NewStruct() *workflow_edgeR {
	return &workflow_edgeR{}
}

func (o *WorkflowEdge) GetWorkflow() *Workflow {
	if o == nil {
		return nil
	}

	return o.R.GetWorkflow()
}

func (r *workflow_edgeR) GetWorkflow() *Workflow {
	if r == nil {
		return nil
	}

	return r.Workflow
}

// workflow_edgeL is where Load methods for each relationship are stored.
type workflow_edgeL struct{}

var (
	workflow_edgeAllColumns            = []string{"id", "workflow_id", "edge_id", "source", "target", "source_handle", "type", "animated", "style", "label", "label_style", "created_at", "updated_at"}
	workflow_edgeColumnsWithoutDefault = []string{"workflow_id", "edge_id", "source", "target"}
	workflow_edgeColumnsWithDefault    = []string{"id", "source_handle", "type", "animated", "style", "label", "label_style", "created_at", "updated_at"}
	workflow_edgePrimaryKeyColumns     = []string{"id"}
	workflow_edgeGeneratedColumns      = []string{}
)

type (
	// WorkflowEdgeSlice is an alias for a slice of pointers to WorkflowEdge.
	// This should almost always be used instead of []WorkflowEdge.
	WorkflowEdgeSlice []*WorkflowEdge
	// WorkflowEdgeHook is the signature for custom WorkflowEdge hook methods
	WorkflowEdgeHook func(context.Context, boil.ContextExecutor, *WorkflowEdge) error

	workflow_edgeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workflow_edgeType                 = reflect.TypeOf(&WorkflowEdge{})
	workflow_edgeMapping              = queries.MakeStructMapping(workflow_edgeType)
	workflow_edgePrimaryKeyMapping, _ = queries.BindMapping(workflow_edgeType, workflow_edgeMapping, workflow_edgePrimaryKeyColumns)
	workflow_edgeInsertCacheMut       sync.RWMutex
	workflow_edgeInsertCache          = make(map[string]insertCache)
	workflow_edgeUpdateCacheMut       sync.RWMutex
	workflow_edgeUpdateCache          = make(map[string]updateCache)
	workflow_edgeUpsertCacheMut       sync.RWMutex
	workflow_edgeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workflow_edgeAfterSelectMu sync.Mutex
var workflow_edgeAfterSelectHooks []WorkflowEdgeHook

var workflow_edgeBeforeInsertMu sync.Mutex
var workflow_edgeBeforeInsertHooks []WorkflowEdgeHook
var workflow_edgeAfterInsertMu sync.Mutex
var workflow_edgeAfterInsertHooks []WorkflowEdgeHook

var workflow_edgeBeforeUpdateMu sync.Mutex
var workflow_edgeBeforeUpdateHooks []WorkflowEdgeHook
var workflow_edgeAfterUpdateMu sync.Mutex
var workflow_edgeAfterUpdateHooks []WorkflowEdgeHook

var workflow_edgeBeforeDeleteMu sync.Mutex
var workflow_edgeBeforeDeleteHooks []WorkflowEdgeHook
var workflow_edgeAfterDeleteMu sync.Mutex
var workflow_edgeAfterDeleteHooks []WorkflowEdgeHook

var workflow_edgeBeforeUpsertMu sync.Mutex
var workflow_edgeBeforeUpsertHooks []WorkflowEdgeHook
var workflow_edgeAfterUpsertMu sync.Mutex
var workflow_edgeAfterUpsertHooks []WorkflowEdgeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkflowEdge) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_edgeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkflowEdge) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_edgeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkflowEdge) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_edgeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkflowEdge) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_edgeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkflowEdge) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_edgeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkflowEdge) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_edgeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkflowEdge) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_edgeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkflowEdge) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_edgeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkflowEdge) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_edgeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkflowEdgeHook registers your hook function for all future operations.
func AddWorkflowEdgeHook(hookPoint boil.HookPoint, workflow_edgeHook WorkflowEdgeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workflow_edgeAfterSelectMu.Lock()
		workflow_edgeAfterSelectHooks = append(workflow_edgeAfterSelectHooks, workflow_edgeHook)
		workflow_edgeAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workflow_edgeBeforeInsertMu.Lock()
		workflow_edgeBeforeInsertHooks = append(workflow_edgeBeforeInsertHooks, workflow_edgeHook)
		workflow_edgeBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workflow_edgeAfterInsertMu.Lock()
		workflow_edgeAfterInsertHooks = append(workflow_edgeAfterInsertHooks, workflow_edgeHook)
		workflow_edgeAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workflow_edgeBeforeUpdateMu.Lock()
		workflow_edgeBeforeUpdateHooks = append(workflow_edgeBeforeUpdateHooks, workflow_edgeHook)
		workflow_edgeBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workflow_edgeAfterUpdateMu.Lock()
		workflow_edgeAfterUpdateHooks = append(workflow_edgeAfterUpdateHooks, workflow_edgeHook)
		workflow_edgeAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workflow_edgeBeforeDeleteMu.Lock()
		workflow_edgeBeforeDeleteHooks = append(workflow_edgeBeforeDeleteHooks, workflow_edgeHook)
		workflow_edgeBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workflow_edgeAfterDeleteMu.Lock()
		workflow_edgeAfterDeleteHooks = append(workflow_edgeAfterDeleteHooks, workflow_edgeHook)
		workflow_edgeAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workflow_edgeBeforeUpsertMu.Lock()
		workflow_edgeBeforeUpsertHooks = append(workflow_edgeBeforeUpsertHooks, workflow_edgeHook)
		workflow_edgeBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workflow_edgeAfterUpsertMu.Lock()
		workflow_edgeAfterUpsertHooks = append(workflow_edgeAfterUpsertHooks, workflow_edgeHook)
		workflow_edgeAfterUpsertMu.Unlock()
	}
}

// One returns a single workflow_edge record from the query.
func (q workflow_edgeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkflowEdge, error) {
	o := &WorkflowEdge{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for workflow_edges")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkflowEdge records from the query.
func (q workflow_edgeQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkflowEdgeSlice, error) {
	var o []*WorkflowEdge

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to WorkflowEdge slice")
	}

	if len(workflow_edgeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkflowEdge records in the query.
func (q workflow_edgeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count workflow_edges rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workflow_edgeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if workflow_edges exists")
	}

	return count > 0, nil
}

// Workflow pointed to by the foreign key.
func (o *WorkflowEdge) Workflow(mods ...qm.QueryMod) workflowQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkflowID),
	}

	queryMods = append(queryMods, mods...)

	return Workflows(queryMods...)
}

// LoadWorkflow allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workflow_edgeL) LoadWorkflow(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkflowEdge any, mods queries.Applicator) error {
	var slice []*WorkflowEdge
	var object *WorkflowEdge

	if singular {
		var ok bool
		object, ok = maybeWorkflowEdge.(*WorkflowEdge)
		if !ok {
			object = new(WorkflowEdge)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkflowEdge)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkflowEdge))
			}
		}
	} else {
		s, ok := maybeWorkflowEdge.(*[]*WorkflowEdge)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkflowEdge)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkflowEdge))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workflow_edgeR{}
		}
		args[object.WorkflowID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workflow_edgeR{}
			}

			args[obj.WorkflowID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workflows`),
		qm.WhereIn(`workflows.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Workflow")
	}

	var resultSlice []*Workflow
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Workflow")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workflows")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workflows")
	}

	if len(workflowAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Workflow = foreign
		if foreign.R == nil {
			foreign.R = &workflowR{}
		}
		foreign.R.WorkflowEdges = append(foreign.R.WorkflowEdges, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkflowID == foreign.ID {
				local.R.Workflow = foreign
				if foreign.R == nil {
					foreign.R = &workflowR{}
				}
				foreign.R.WorkflowEdges = append(foreign.R.WorkflowEdges, local)
				break
			}
		}
	}

	return nil
}

// SetWorkflow of the workflow_edge to the related item.
// Sets o.R.Workflow to related.
// Adds o to related.R.WorkflowEdges.
func (o *WorkflowEdge) SetWorkflow(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Workflow) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workflow_edges\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workflow_id"}),
		strmangle.WhereClause("\"", "\"", 2, workflow_edgePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkflowID = related.ID
	if o.R == nil {
		o.R = &workflow_edgeR{
			Workflow: related,
		}
	} else {
		o.R.Workflow = related
	}

	if related.R == nil {
		related.R = &workflowR{
			WorkflowEdges: WorkflowEdgeSlice{o},
		}
	} else {
		related.R.WorkflowEdges = append(related.R.WorkflowEdges, o)
	}

	return nil
}

// WorkflowEdges retrieves all the records using an executor.
func WorkflowEdges(mods ...qm.QueryMod) workflow_edgeQuery {
	mods = append(mods, qm.From("\"workflow_edges\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workflow_edges\".*"})
	}

	return workflow_edgeQuery{q}
}

// FindWorkflowEdge retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkflowEdge(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WorkflowEdge, error) {
	workflow_edgeObj := &WorkflowEdge{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workflow_edges\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workflow_edgeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from workflow_edges")
	}

	if err = workflow_edgeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workflow_edgeObj, err
	}

	return workflow_edgeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkflowEdge) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no workflow_edges provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workflow_edgeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workflow_edgeInsertCacheMut.RLock()
	cache, cached := workflow_edgeInsertCache[key]
	workflow_edgeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workflow_edgeAllColumns,
			workflow_edgeColumnsWithDefault,
			workflow_edgeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workflow_edgeType, workflow_edgeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workflow_edgeType, workflow_edgeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workflow_edges\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workflow_edges\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into workflow_edges")
	}

	if !cached {
		workflow_edgeInsertCacheMut.Lock()
		workflow_edgeInsertCache[key] = cache
		workflow_edgeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkflowEdge.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkflowEdge) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workflow_edgeUpdateCacheMut.RLock()
	cache, cached := workflow_edgeUpdateCache[key]
	workflow_edgeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workflow_edgeAllColumns,
			workflow_edgePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update workflow_edges, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workflow_edges\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workflow_edgePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workflow_edgeType, workflow_edgeMapping, append(wl, workflow_edgePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update workflow_edges row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for workflow_edges")
	}

	if !cached {
		workflow_edgeUpdateCacheMut.Lock()
		workflow_edgeUpdateCache[key] = cache
		workflow_edgeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workflow_edgeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for workflow_edges")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for workflow_edges")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkflowEdgeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workflow_edgePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workflow_edges\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workflow_edgePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in workflow_edge slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all workflow_edge")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkflowEdge) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no workflow_edges provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workflow_edgeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workflow_edgeUpsertCacheMut.RLock()
	cache, cached := workflow_edgeUpsertCache[key]
	workflow_edgeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workflow_edgeAllColumns,
			workflow_edgeColumnsWithDefault,
			workflow_edgeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workflow_edgeAllColumns,
			workflow_edgePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert workflow_edges, could not build update column list")
		}

		ret := strmangle.SetComplement(workflow_edgeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workflow_edgePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert workflow_edges, could not build conflict column list")
			}

			conflict = make([]string, len(workflow_edgePrimaryKeyColumns))
			copy(conflict, workflow_edgePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workflow_edges\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workflow_edgeType, workflow_edgeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workflow_edgeType, workflow_edgeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert workflow_edges")
	}

	if !cached {
		workflow_edgeUpsertCacheMut.Lock()
		workflow_edgeUpsertCache[key] = cache
		workflow_edgeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkflowEdge record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkflowEdge) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no WorkflowEdge provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workflow_edgePrimaryKeyMapping)
	sql := "DELETE FROM \"workflow_edges\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from workflow_edges")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for workflow_edges")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workflow_edgeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no workflow_edgeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from workflow_edges")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for workflow_edges")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkflowEdgeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workflow_edgeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workflow_edgePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workflow_edges\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workflow_edgePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from workflow_edge slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for workflow_edges")
	}

	if len(workflow_edgeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkflowEdge) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkflowEdge(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkflowEdgeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkflowEdgeSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workflow_edgePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workflow_edges\".* FROM \"workflow_edges\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workflow_edgePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WorkflowEdgeSlice")
	}

	*o = slice

	return nil
}

// WorkflowEdgeExists checks if the WorkflowEdge row exists.
func WorkflowEdgeExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workflow_edges\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if workflow_edges exists")
	}

	return exists, nil
}

// Exists checks if the WorkflowEdge row exists.
func (o *WorkflowEdge) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkflowEdgeExists(ctx, exec, o.ID)
}
