// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WorkflowNode is an object representing the database table.
type WorkflowNode struct {
	ID         string     `boil:"id" json:"id" toml:"id" yaml:"id"`
	WorkflowID string     `boil:"workflow_id" json:"workflow_id" toml:"workflow_id" yaml:"workflow_id"`
	NodeID     string     `boil:"node_id" json:"node_id" toml:"node_id" yaml:"node_id"`
	Type       string     `boil:"type" json:"type" toml:"type" yaml:"type"`
	Position   types.JSON `boil:"position" json:"position" toml:"position" yaml:"position"`
	Data       null.JSON  `boil:"data" json:"data,omitempty" toml:"data" yaml:"data,omitempty"`
	CreatedAt  null.Time  `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt  null.Time  `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *workflow_nodeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workflow_nodeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkflowNodeColumns = struct {
	ID         string
	WorkflowID string
	NodeID     string
	Type       string
	Position   string
	Data       string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "id",
	WorkflowID: "workflow_id",
	NodeID:     "node_id",
	Type:       "type",
	Position:   "position",
	Data:       "data",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

var WorkflowNodeTableColumns = struct {
	ID         string
	WorkflowID string
	NodeID     string
	Type       string
	Position   string
	Data       string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "workflow_nodes.id",
	WorkflowID: "workflow_nodes.workflow_id",
	NodeID:     "workflow_nodes.node_id",
	Type:       "workflow_nodes.type",
	Position:   "workflow_nodes.position",
	Data:       "workflow_nodes.data",
	CreatedAt:  "workflow_nodes.created_at",
	UpdatedAt:  "workflow_nodes.updated_at",
}

// Generated where

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var WorkflowNodeWhere = struct {
	ID         whereHelperstring
	WorkflowID whereHelperstring
	NodeID     whereHelperstring
	Type       whereHelperstring
	Position   whereHelpertypes_JSON
	Data       whereHelpernull_JSON
	CreatedAt  whereHelpernull_Time
	UpdatedAt  whereHelpernull_Time
}{
	ID:         whereHelperstring{field: "\"workflow_nodes\".\"id\""},
	WorkflowID: whereHelperstring{field: "\"workflow_nodes\".\"workflow_id\""},
	NodeID:     whereHelperstring{field: "\"workflow_nodes\".\"node_id\""},
	Type:       whereHelperstring{field: "\"workflow_nodes\".\"type\""},
	Position:   whereHelpertypes_JSON{field: "\"workflow_nodes\".\"position\""},
	Data:       whereHelpernull_JSON{field: "\"workflow_nodes\".\"data\""},
	CreatedAt:  whereHelpernull_Time{field: "\"workflow_nodes\".\"created_at\""},
	UpdatedAt:  whereHelpernull_Time{field: "\"workflow_nodes\".\"updated_at\""},
}

// WorkflowNodeRels is where relationship names are stored.
var WorkflowNodeRels = struct {
	Workflow string
}{
	Workflow: "Workflow",
}

// workflow_nodeR is where relationships are stored.
type workflow_nodeR struct {
	Workflow *Workflow `boil:"Workflow" json:"Workflow" toml:"Workflow" yaml:"Workflow"`
}

// NewStruct creates a new relationship struct
func (*workflow_nodeR) NewStruct() *workflow_nodeR {
	return &workflow_nodeR{}
}

func (o *WorkflowNode) GetWorkflow() *Workflow {
	if o == nil {
		return nil
	}

	return o.R.GetWorkflow()
}

func (r *workflow_nodeR) GetWorkflow() *Workflow {
	if r == nil {
		return nil
	}

	return r.Workflow
}

// workflow_nodeL is where Load methods for each relationship are stored.
type workflow_nodeL struct{}

var (
	workflow_nodeAllColumns            = []string{"id", "workflow_id", "node_id", "type", "position", "data", "created_at", "updated_at"}
	workflow_nodeColumnsWithoutDefault = []string{"workflow_id", "node_id", "type", "position"}
	workflow_nodeColumnsWithDefault    = []string{"id", "data", "created_at", "updated_at"}
	workflow_nodePrimaryKeyColumns     = []string{"id"}
	workflow_nodeGeneratedColumns      = []string{}
)

type (
	// WorkflowNodeSlice is an alias for a slice of pointers to WorkflowNode.
	// This should almost always be used instead of []WorkflowNode.
	WorkflowNodeSlice []*WorkflowNode
	// WorkflowNodeHook is the signature for custom WorkflowNode hook methods
	WorkflowNodeHook func(context.Context, boil.ContextExecutor, *WorkflowNode) error

	workflow_nodeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workflow_nodeType                 = reflect.TypeOf(&WorkflowNode{})
	workflow_nodeMapping              = queries.MakeStructMapping(workflow_nodeType)
	workflow_nodePrimaryKeyMapping, _ = queries.BindMapping(workflow_nodeType, workflow_nodeMapping, workflow_nodePrimaryKeyColumns)
	workflow_nodeInsertCacheMut       sync.RWMutex
	workflow_nodeInsertCache          = make(map[string]insertCache)
	workflow_nodeUpdateCacheMut       sync.RWMutex
	workflow_nodeUpdateCache          = make(map[string]updateCache)
	workflow_nodeUpsertCacheMut       sync.RWMutex
	workflow_nodeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workflow_nodeAfterSelectMu sync.Mutex
var workflow_nodeAfterSelectHooks []WorkflowNodeHook

var workflow_nodeBeforeInsertMu sync.Mutex
var workflow_nodeBeforeInsertHooks []WorkflowNodeHook
var workflow_nodeAfterInsertMu sync.Mutex
var workflow_nodeAfterInsertHooks []WorkflowNodeHook

var workflow_nodeBeforeUpdateMu sync.Mutex
var workflow_nodeBeforeUpdateHooks []WorkflowNodeHook
var workflow_nodeAfterUpdateMu sync.Mutex
var workflow_nodeAfterUpdateHooks []WorkflowNodeHook

var workflow_nodeBeforeDeleteMu sync.Mutex
var workflow_nodeBeforeDeleteHooks []WorkflowNodeHook
var workflow_nodeAfterDeleteMu sync.Mutex
var workflow_nodeAfterDeleteHooks []WorkflowNodeHook

var workflow_nodeBeforeUpsertMu sync.Mutex
var workflow_nodeBeforeUpsertHooks []WorkflowNodeHook
var workflow_nodeAfterUpsertMu sync.Mutex
var workflow_nodeAfterUpsertHooks []WorkflowNodeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkflowNode) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_nodeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkflowNode) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_nodeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkflowNode) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_nodeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkflowNode) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_nodeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkflowNode) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_nodeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkflowNode) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_nodeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkflowNode) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_nodeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkflowNode) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_nodeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkflowNode) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workflow_nodeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkflowNodeHook registers your hook function for all future operations.
func AddWorkflowNodeHook(hookPoint boil.HookPoint, workflow_nodeHook WorkflowNodeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workflow_nodeAfterSelectMu.Lock()
		workflow_nodeAfterSelectHooks = append(workflow_nodeAfterSelectHooks, workflow_nodeHook)
		workflow_nodeAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workflow_nodeBeforeInsertMu.Lock()
		workflow_nodeBeforeInsertHooks = append(workflow_nodeBeforeInsertHooks, workflow_nodeHook)
		workflow_nodeBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workflow_nodeAfterInsertMu.Lock()
		workflow_nodeAfterInsertHooks = append(workflow_nodeAfterInsertHooks, workflow_nodeHook)
		workflow_nodeAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workflow_nodeBeforeUpdateMu.Lock()
		workflow_nodeBeforeUpdateHooks = append(workflow_nodeBeforeUpdateHooks, workflow_nodeHook)
		workflow_nodeBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workflow_nodeAfterUpdateMu.Lock()
		workflow_nodeAfterUpdateHooks = append(workflow_nodeAfterUpdateHooks, workflow_nodeHook)
		workflow_nodeAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workflow_nodeBeforeDeleteMu.Lock()
		workflow_nodeBeforeDeleteHooks = append(workflow_nodeBeforeDeleteHooks, workflow_nodeHook)
		workflow_nodeBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workflow_nodeAfterDeleteMu.Lock()
		workflow_nodeAfterDeleteHooks = append(workflow_nodeAfterDeleteHooks, workflow_nodeHook)
		workflow_nodeAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workflow_nodeBeforeUpsertMu.Lock()
		workflow_nodeBeforeUpsertHooks = append(workflow_nodeBeforeUpsertHooks, workflow_nodeHook)
		workflow_nodeBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workflow_nodeAfterUpsertMu.Lock()
		workflow_nodeAfterUpsertHooks = append(workflow_nodeAfterUpsertHooks, workflow_nodeHook)
		workflow_nodeAfterUpsertMu.Unlock()
	}
}

// One returns a single workflow_node record from the query.
func (q workflow_nodeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkflowNode, error) {
	o := &WorkflowNode{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for workflow_nodes")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkflowNode records from the query.
func (q workflow_nodeQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkflowNodeSlice, error) {
	var o []*WorkflowNode

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to WorkflowNode slice")
	}

	if len(workflow_nodeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkflowNode records in the query.
func (q workflow_nodeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count workflow_nodes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workflow_nodeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if workflow_nodes exists")
	}

	return count > 0, nil
}

// Workflow pointed to by the foreign key.
func (o *WorkflowNode) Workflow(mods ...qm.QueryMod) workflowQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkflowID),
	}

	queryMods = append(queryMods, mods...)

	return Workflows(queryMods...)
}

// LoadWorkflow allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workflow_nodeL) LoadWorkflow(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkflowNode any, mods queries.Applicator) error {
	var slice []*WorkflowNode
	var object *WorkflowNode

	if singular {
		var ok bool
		object, ok = maybeWorkflowNode.(*WorkflowNode)
		if !ok {
			object = new(WorkflowNode)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkflowNode)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkflowNode))
			}
		}
	} else {
		s, ok := maybeWorkflowNode.(*[]*WorkflowNode)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkflowNode)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkflowNode))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workflow_nodeR{}
		}
		args[object.WorkflowID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workflow_nodeR{}
			}

			args[obj.WorkflowID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workflows`),
		qm.WhereIn(`workflows.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Workflow")
	}

	var resultSlice []*Workflow
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Workflow")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workflows")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workflows")
	}

	if len(workflowAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Workflow = foreign
		if foreign.R == nil {
			foreign.R = &workflowR{}
		}
		foreign.R.WorkflowNodes = append(foreign.R.WorkflowNodes, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkflowID == foreign.ID {
				local.R.Workflow = foreign
				if foreign.R == nil {
					foreign.R = &workflowR{}
				}
				foreign.R.WorkflowNodes = append(foreign.R.WorkflowNodes, local)
				break
			}
		}
	}

	return nil
}

// SetWorkflow of the workflow_node to the related item.
// Sets o.R.Workflow to related.
// Adds o to related.R.WorkflowNodes.
func (o *WorkflowNode) SetWorkflow(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Workflow) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workflow_nodes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workflow_id"}),
		strmangle.WhereClause("\"", "\"", 2, workflow_nodePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkflowID = related.ID
	if o.R == nil {
		o.R = &workflow_nodeR{
			Workflow: related,
		}
	} else {
		o.R.Workflow = related
	}

	if related.R == nil {
		related.R = &workflowR{
			WorkflowNodes: WorkflowNodeSlice{o},
		}
	} else {
		related.R.WorkflowNodes = append(related.R.WorkflowNodes, o)
	}

	return nil
}

// WorkflowNodes retrieves all the records using an executor.
func WorkflowNodes(mods ...qm.QueryMod) workflow_nodeQuery {
	mods = append(mods, qm.From("\"workflow_nodes\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workflow_nodes\".*"})
	}

	return workflow_nodeQuery{q}
}

// FindWorkflowNode retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkflowNode(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WorkflowNode, error) {
	workflow_nodeObj := &WorkflowNode{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workflow_nodes\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workflow_nodeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from workflow_nodes")
	}

	if err = workflow_nodeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workflow_nodeObj, err
	}

	return workflow_nodeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkflowNode) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no workflow_nodes provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workflow_nodeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workflow_nodeInsertCacheMut.RLock()
	cache, cached := workflow_nodeInsertCache[key]
	workflow_nodeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workflow_nodeAllColumns,
			workflow_nodeColumnsWithDefault,
			workflow_nodeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workflow_nodeType, workflow_nodeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workflow_nodeType, workflow_nodeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workflow_nodes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workflow_nodes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into workflow_nodes")
	}

	if !cached {
		workflow_nodeInsertCacheMut.Lock()
		workflow_nodeInsertCache[key] = cache
		workflow_nodeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkflowNode.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkflowNode) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workflow_nodeUpdateCacheMut.RLock()
	cache, cached := workflow_nodeUpdateCache[key]
	workflow_nodeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workflow_nodeAllColumns,
			workflow_nodePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update workflow_nodes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workflow_nodes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workflow_nodePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workflow_nodeType, workflow_nodeMapping, append(wl, workflow_nodePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update workflow_nodes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for workflow_nodes")
	}

	if !cached {
		workflow_nodeUpdateCacheMut.Lock()
		workflow_nodeUpdateCache[key] = cache
		workflow_nodeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workflow_nodeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for workflow_nodes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for workflow_nodes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkflowNodeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workflow_nodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workflow_nodes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workflow_nodePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in workflow_node slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all workflow_node")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkflowNode) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no workflow_nodes provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workflow_nodeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workflow_nodeUpsertCacheMut.RLock()
	cache, cached := workflow_nodeUpsertCache[key]
	workflow_nodeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workflow_nodeAllColumns,
			workflow_nodeColumnsWithDefault,
			workflow_nodeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workflow_nodeAllColumns,
			workflow_nodePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert workflow_nodes, could not build update column list")
		}

		ret := strmangle.SetComplement(workflow_nodeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workflow_nodePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert workflow_nodes, could not build conflict column list")
			}

			conflict = make([]string, len(workflow_nodePrimaryKeyColumns))
			copy(conflict, workflow_nodePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workflow_nodes\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workflow_nodeType, workflow_nodeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workflow_nodeType, workflow_nodeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert workflow_nodes")
	}

	if !cached {
		workflow_nodeUpsertCacheMut.Lock()
		workflow_nodeUpsertCache[key] = cache
		workflow_nodeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkflowNode record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkflowNode) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no WorkflowNode provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workflow_nodePrimaryKeyMapping)
	sql := "DELETE FROM \"workflow_nodes\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from workflow_nodes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for workflow_nodes")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workflow_nodeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no workflow_nodeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from workflow_nodes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for workflow_nodes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkflowNodeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workflow_nodeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workflow_nodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workflow_nodes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workflow_nodePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from workflow_node slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for workflow_nodes")
	}

	if len(workflow_nodeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkflowNode) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkflowNode(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkflowNodeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkflowNodeSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workflow_nodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workflow_nodes\".* FROM \"workflow_nodes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workflow_nodePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WorkflowNodeSlice")
	}

	*o = slice

	return nil
}

// WorkflowNodeExists checks if the WorkflowNode row exists.
func WorkflowNodeExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workflow_nodes\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if workflow_nodes exists")
	}

	return exists, nil
}

// Exists checks if the WorkflowNode row exists.
func (o *WorkflowNode) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkflowNodeExists(ctx, exec, o.ID)
}
