// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWorkflows(t *testing.T) {
	t.Parallel()

	query := Workflows()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWorkflowsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Workflows().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkflowsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Workflows().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Workflows().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkflowsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkflowSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Workflows().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkflowsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WorkflowExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Workflow exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WorkflowExists to return true, but got false.")
	}
}

func testWorkflowsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	workflowFound, err := FindWorkflow(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if workflowFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWorkflowsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Workflows().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWorkflowsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Workflows().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWorkflowsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	workflowOne := &Workflow{}
	workflowTwo := &Workflow{}
	if err = randomize.Struct(seed, workflowOne, workflowDBTypes, false, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}
	if err = randomize.Struct(seed, workflowTwo, workflowDBTypes, false, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workflowOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workflowTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Workflows().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWorkflowsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	workflowOne := &Workflow{}
	workflowTwo := &Workflow{}
	if err = randomize.Struct(seed, workflowOne, workflowDBTypes, false, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}
	if err = randomize.Struct(seed, workflowTwo, workflowDBTypes, false, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workflowOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workflowTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Workflows().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func workflowBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
	*o = Workflow{}
	return nil
}

func workflowAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
	*o = Workflow{}
	return nil
}

func workflowAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
	*o = Workflow{}
	return nil
}

func workflowBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
	*o = Workflow{}
	return nil
}

func workflowAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
	*o = Workflow{}
	return nil
}

func workflowBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
	*o = Workflow{}
	return nil
}

func workflowAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
	*o = Workflow{}
	return nil
}

func workflowBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
	*o = Workflow{}
	return nil
}

func workflowAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Workflow) error {
	*o = Workflow{}
	return nil
}

func testWorkflowsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Workflow{}
	o := &Workflow{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, workflowDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Workflow object: %s", err)
	}

	AddWorkflowHook(boil.BeforeInsertHook, workflowBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	workflowBeforeInsertHooks = []WorkflowHook{}

	AddWorkflowHook(boil.AfterInsertHook, workflowAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	workflowAfterInsertHooks = []WorkflowHook{}

	AddWorkflowHook(boil.AfterSelectHook, workflowAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	workflowAfterSelectHooks = []WorkflowHook{}

	AddWorkflowHook(boil.BeforeUpdateHook, workflowBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	workflowBeforeUpdateHooks = []WorkflowHook{}

	AddWorkflowHook(boil.AfterUpdateHook, workflowAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	workflowAfterUpdateHooks = []WorkflowHook{}

	AddWorkflowHook(boil.BeforeDeleteHook, workflowBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	workflowBeforeDeleteHooks = []WorkflowHook{}

	AddWorkflowHook(boil.AfterDeleteHook, workflowAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	workflowAfterDeleteHooks = []WorkflowHook{}

	AddWorkflowHook(boil.BeforeUpsertHook, workflowBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	workflowBeforeUpsertHooks = []WorkflowHook{}

	AddWorkflowHook(boil.AfterUpsertHook, workflowAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	workflowAfterUpsertHooks = []WorkflowHook{}
}

func testWorkflowsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Workflows().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkflowsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(workflowPrimaryKeyColumns, workflowColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Workflows().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkflowToManyWorkflowEdges(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Workflow
	var b, c WorkflowEdge

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, workflow_edgeDBTypes, false, workflow_edgeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, workflow_edgeDBTypes, false, workflow_edgeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.WorkflowID = a.ID
	c.WorkflowID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.WorkflowEdges().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.WorkflowID == b.WorkflowID {
			bFound = true
		}
		if v.WorkflowID == c.WorkflowID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := WorkflowSlice{&a}
	if err = a.L.LoadWorkflowEdges(ctx, tx, false, (*[]*Workflow)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WorkflowEdges); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.WorkflowEdges = nil
	if err = a.L.LoadWorkflowEdges(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WorkflowEdges); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testWorkflowToManyWorkflowNodes(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Workflow
	var b, c WorkflowNode

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, workflow_nodeDBTypes, false, workflow_nodeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, workflow_nodeDBTypes, false, workflow_nodeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.WorkflowID = a.ID
	c.WorkflowID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.WorkflowNodes().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.WorkflowID == b.WorkflowID {
			bFound = true
		}
		if v.WorkflowID == c.WorkflowID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := WorkflowSlice{&a}
	if err = a.L.LoadWorkflowNodes(ctx, tx, false, (*[]*Workflow)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WorkflowNodes); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.WorkflowNodes = nil
	if err = a.L.LoadWorkflowNodes(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WorkflowNodes); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testWorkflowToManyAddOpWorkflowEdges(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Workflow
	var b, c, d, e WorkflowEdge

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workflowDBTypes, false, strmangle.SetComplement(workflowPrimaryKeyColumns, workflowColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*WorkflowEdge{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, workflow_edgeDBTypes, false, strmangle.SetComplement(workflow_edgePrimaryKeyColumns, workflow_edgeColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*WorkflowEdge{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddWorkflowEdges(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.WorkflowID {
			t.Error("foreign key was wrong value", a.ID, first.WorkflowID)
		}
		if a.ID != second.WorkflowID {
			t.Error("foreign key was wrong value", a.ID, second.WorkflowID)
		}

		if first.R.Workflow != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Workflow != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.WorkflowEdges[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.WorkflowEdges[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.WorkflowEdges().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testWorkflowToManyAddOpWorkflowNodes(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Workflow
	var b, c, d, e WorkflowNode

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workflowDBTypes, false, strmangle.SetComplement(workflowPrimaryKeyColumns, workflowColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*WorkflowNode{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, workflow_nodeDBTypes, false, strmangle.SetComplement(workflow_nodePrimaryKeyColumns, workflow_nodeColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*WorkflowNode{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddWorkflowNodes(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.WorkflowID {
			t.Error("foreign key was wrong value", a.ID, first.WorkflowID)
		}
		if a.ID != second.WorkflowID {
			t.Error("foreign key was wrong value", a.ID, second.WorkflowID)
		}

		if first.R.Workflow != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Workflow != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.WorkflowNodes[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.WorkflowNodes[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.WorkflowNodes().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testWorkflowsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkflowsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkflowSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkflowsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Workflows().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	workflowDBTypes = map[string]string{`ID`: `uuid`, `Name`: `character varying`, `Description`: `text`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_               = bytes.MinRead
)

func testWorkflowsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(workflowPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(workflowAllColumns) == len(workflowPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Workflows().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWorkflowsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(workflowAllColumns) == len(workflowPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Workflow{}
	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Workflows().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workflowDBTypes, true, workflowPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(workflowAllColumns, workflowPrimaryKeyColumns) {
		fields = workflowAllColumns
	} else {
		fields = strmangle.SetComplement(
			workflowAllColumns,
			workflowPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WorkflowSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWorkflowsUpsert(t *testing.T) {
	t.Parallel()

	if len(workflowAllColumns) == len(workflowPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Workflow{}
	if err = randomize.Struct(seed, &o, workflowDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Workflow: %s", err)
	}

	count, err := Workflows().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, workflowDBTypes, false, workflowPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Workflow struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Workflow: %s", err)
	}

	count, err = Workflows().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
